/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bfh_ticket_TicketMatch */

#ifndef _Included_com_bfh_ticket_TicketMatch
#define _Included_com_bfh_ticket_TicketMatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bfh_ticket_TicketMatch
 * Method:    getTicket
 * Signature: (J)Lcom/bfh/ticket/Ticket;
 */
JNIEXPORT jobject JNICALL Java_com_bfh_ticket_TicketMatch_getTicket
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
