/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bfh_ticket_MetadataReader */

#ifndef _Included_com_bfh_ticket_MetadataReader
#define _Included_com_bfh_ticket_MetadataReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bfh_ticket_MetadataReader
 * Method:    initialize
 * Signature: (Lcom/bfh/ticket/Algorithm;Lcom/bfh/ticket/MetadataReaderOptions;)J
 */
JNIEXPORT jlong JNICALL Java_com_bfh_ticket_MetadataReader_initialize
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_bfh_ticket_MetadataReader
 * Method:    read
 * Signature: (JJLcom/bfh/ticket/TicketImage;)Lcom/bfh/ticket/Metadata;
 */
JNIEXPORT jobject JNICALL Java_com_bfh_ticket_MetadataReader_read
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     com_bfh_ticket_MetadataReader
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_bfh_ticket_MetadataReader_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
