/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bfh_ticket_TicketMatch */

#ifndef _Included_com_bfh_ticket_TicketMatch
#define _Included_com_bfh_ticket_TicketMatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bfh_ticket_TicketMatch
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bfh_ticket_TicketMatch_getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_bfh_ticket_TicketMatch
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_bfh_ticket_TicketMatch_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
