/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bfh_ticket_Ticket */

#ifndef _Included_com_bfh_ticket_Ticket
#define _Included_com_bfh_ticket_Ticket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bfh_ticket_Ticket
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_bfh_ticket_Ticket_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
