/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bfh_ticket_Metadata */

#ifndef _Included_com_bfh_ticket_Metadata
#define _Included_com_bfh_ticket_Metadata
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bfh_ticket_Metadata
 * Method:    getTexts
 * Signature: (J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_bfh_ticket_Metadata_getTexts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_bfh_ticket_Metadata
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_bfh_ticket_Metadata_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
