/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bfh_ticket_Cti */

#ifndef _Included_com_bfh_ticket_Cti
#define _Included_com_bfh_ticket_Cti
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bfh_ticket_Cti
 * Method:    matcher
 * Signature: (Ljava/lang/String;)Lcom/bfh/ticket/Matcher;
 */
JNIEXPORT jobject JNICALL Java_com_bfh_ticket_Cti_matcher
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bfh_ticket_Cti
 * Method:    reader
 * Signature: (Ljava/lang/String;)Lcom/bfh/ticket/MetadataReader;
 */
JNIEXPORT jobject JNICALL Java_com_bfh_ticket_Cti_reader
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
