/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bfh_ticket_Cti */

#ifndef _Included_com_bfh_ticket_Cti
#define _Included_com_bfh_ticket_Cti
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bfh_ticket_Cti
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_bfh_ticket_Cti_hello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bfh_ticket_Cti
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bfh_ticket_Cti_helloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
